// Copyright (c) 2020 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=87df48763ce52dae62860cd60e386e64b5da480d$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_POWER_POLICY_CONTROLLER_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_POWER_POLICY_CONTROLLER_CPPTOC_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_power_policy_controller_capi.h"
#include "include/cef_power_policy_controller.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class CefPowerPolicyControllerCppToC
    : public CefCppToCRefCounted<CefPowerPolicyControllerCppToC,
                                 CefPowerPolicyController,
                                 cef_power_policy_controller_t> {
 public:
  CefPowerPolicyControllerCppToC();
  virtual ~CefPowerPolicyControllerCppToC();
};

#endif  // CEF_LIBCEF_DLL_CPPTOC_POWER_POLICY_CONTROLLER_CPPTOC_H_
